-- WHAT’S THE OVERALL CHURN RATE?
SELECT
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(CHURN) AS CHURNED_CUSTOMERS,
	(SUM(CHURN)/ COUNT(*))* 100 AS OVERALL_CHURN_RATE
FROM
	SUBSCRIPTIONS;

-- WHICH SUBSCRIPTION TYPE HAS THE HIGHEST CHURN?
SELECT
	SUBSCRIPTIONTYPE,
	AVG(CHURN) * 100 AS CHURN_PERCENTAGE
FROM
	SUBSCRIPTIONS
GROUP BY
	SUBSCRIPTIONTYPE
ORDER BY
	AVG(CHURN) * 100 DESC ;

-- DOES AGE AFFECT CHURN?
SELECT
	AGE,
	AVG(CHURN) * 100 AS CHURN_RATE
FROM
	CUSTOMERS
JOIN SUBSCRIPTIONS ON
	CUSTOMERS.CUSTOMERID = SUBSCRIPTIONS.CUSTOMERID
GROUP BY
	AGE
ORDER BY
	AGE ASC;

-- DO CUSTOMERS WHO CALL SUPPORT MORE CHURN MORE?
SELECT
	SUPPORTCALLS,
	ROUND(AVG(CHURN) * 100) AS CHURN_RATE
FROM
	USAGE_METRICS
JOIN SUBSCRIPTIONS ON
	USAGE_METRICS.CUSTOMERID = SUBSCRIPTIONS.CUSTOMERID
GROUP BY
	SUPPORTCALLS
ORDER BY
	SUPPORTCALLS ASC;

-- WHO ARE THE TOP 10 HIGH-VALUE CUSTOMERS?
SELECT
	CUSTOMERID,
	TOTALSPEND
FROM
	SUBSCRIPTIONS
ORDER BY
	TOTALSPEND DESC
LIMIT 10;

-- ARE PAYMENT DELAYS LINKED TO CHURN?
SELECT
	PAYMENTDELAY,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(CHURN) AS CHURNED_CUSTOMERS,
	ROUND(AVG(CHURN) * 100) AS CHURN_RATE
FROM
	USAGE_METRICS
JOIN SUBSCRIPTIONS ON
	USAGE_METRICS.CUSTOMERID = SUBSCRIPTIONS.CUSTOMERID
GROUP BY
	PAYMENTDELAY
ORDER BY
	PAYMENTDELAY ASC;

-- CONTRACT LENGTH VS CHURN
SELECT
	CONTRACTLENGTH,
	ROUND(AVG(CHURN) * 100) AS CHURN_RATE
FROM
	SUBSCRIPTIONS
GROUP BY
	CONTRACTLENGTH;

-- GENDER VS CHURN
SELECT
	GENDER,
	ROUND(AVG(CHURN) * 100) AS CHURN_RATE
FROM
	CUSTOMERS
JOIN SUBSCRIPTIONS ON
	CUSTOMERS.CUSTOMERID = SUBSCRIPTIONS.CUSTOMERID
GROUP BY
	GENDER;

-- WHICH TENURE GROUP BRINGS IN MOST REVENUE?
SELECT
	TENURE,
	SUM(TOTALSPEND)
FROM
	CUSTOMERS
JOIN SUBSCRIPTIONS ON
	CUSTOMERS.CUSTOMERID = SUBSCRIPTIONS.CUSTOMERID
GROUP BY
	TENURE
ORDER BY
	SUM(TOTALSPEND) DESC
LIMIT 1;


